# Generated by Django 4.0.4 on 2022-06-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_ids',
            new_name='id_user',
        ),
    ]
